service: my-serverless-api

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  stage: offline

custom:
  dynamodb:
    stages:
      - offline
    start:
      port: 8000
      inMemory: true
      migrate: true
      seed: false

plugins:
  - serverless-dynamodb-local
  - serverless-offline

resources:
  Resources:
    MyTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: myTable-offline
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

functions:
  hello:
    handler: handler.hello
    environment:
      DYNAMODB_TABLE: myTable-offline
      IS_OFFLINE: "true"
    events:
      - http:
          path: hello
          method: get
          cors: true